# Generated by Django 5.1.1 on 2024-10-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures'),
        ),
    ]
