# Generated by Django 5.1.1 on 2024-10-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='picture',
        ),
    ]
